export const projects = [
  {
    title: "Voice Booth",
    description:"Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: "/images/1.png",
    tags: ["JavaScript","Html","Css"],
    source: "https://github.com/mdAsifAhmmed/voice-booth-animation-face",
    visit: "https://mdasifahmmed.github.io/voice-booth-animation-face/",
    id: 0,
  },
  {
    title: "Protflio",
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: "/images/luf.png",
    tags: ["JavaScript","Html","Css" ],
    source: "https://google.com",
    visit: "https://mdasifahmmed.github.io/liveUserFilter/",
    id: 1,
  },
  {
    title: "react video player",
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: "/images/video_player.png",
    tags: ["JavaScript","Html","Css" ],
    source: "https://google.com",
    visit: "https://react-video-player-mao95yh94-mdasifahmmed.vercel.app/",
    id: 7,
  },
  {
    title: "Weather Appse",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/3.png",
    tags: ["JavaScript","Html", "Css"],
    source: "#",
    visit: "https://weather-apps-selet-cuntry-name.netlify.app/",
    id: 2,
  },
  {
    title: "Api Chat Both",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/4.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://apichatboothwithejs.netlify.app/",
    id: 3,
  },
  {
    title: "Password Generator",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/pwg.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://mdasifahmmed.github.io/password-generator/",
    id: 4,
  },
  {
    title: "Simple page",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/wc.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://mdasifahmmed.github.io/welcome-protfio/",
    id: 8,
  },
  {
    title: "COVID-19 CORONAVIRUS",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/coronavires.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://mdasifahmmed.github.io/coronavirus/",
    id: 5,
  },
  {
    title: "Simpole page",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/PORTFOLIOSeven.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://mdasifahmmed.github.io/glozzom/",
    id: 6,
  },
  {
    title: "Simpole page",
    description:"This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/syco.png",
    tags: ["JavaScript", "Html","Css"],
    source: "https://github.com/mdAsifAhmmed/ApiChatBotWithJavascript",
    visit: "https://mdasifahmmed.github.io/sycho/",
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: "Started my journey" },
  { year: 2020, text: "Worked as a freelance developer" },
  { year: 2021, text: "Shared my projects with the world" },
];
